### ISSUE TITLE
Prevent this case is needed "not enough values to unpack"

### ISSUE THREAD

**Issue by agiani99** [Jonas-Verhellen/argenomic#4]
Creating remdesivir analogues through the yaml attached I repeatedly got this error file which I suspect has to do with restrains from descriptors. Any thoughts for me?

Best

Andrea
 

Traceback (most recent call last):
  File "illuminate.py", line 74, in <module>
    illumination(omegaconf.OmegaConf.load(configuration.configuration_file))(configuration.generations)
  File "illuminate.py", line 29, in __call__
    molecules = self.generate_molecules()
  File "illuminate.py", line 52, in generate_molecules
    molecules.extend(self.crossover(molecule_pair))
  File "/home/zaliani/sw/argenomic/argenomic/operations.py", line 39, in __call__
    molecule_cores, molecule_sidechains = self.fragmentate(molecule_pair)
  File "/home/zaliani/sw/argenomic/argenomic/operations.py", line 56, in fragmentate
    _, molecule_frags = map(list, zip(*molecule_frags))
ValueError: not enough values to unpack (expected 2, got 0)

This is the yaml file has been used
[config_az.txt](https://github.com/Jonas-Verhellen/Argenomic/files/4971665/config_az.txt)

**Comment by Jonas-Verhellen** [comment]
Dear Andrea,

Thank you for your issue. I have made the bug fix (see bug-fix branch) and submitted it to the internal review processes. After acceptance of the pull request, the issue should be resolved in the main branch. 

Kind regards,
Jonas

**Comment by agiani99** [comment]
Uau
Fast!
Thx
Andrea


-----Original Message-----
