### ISSUE TITLE
Numpy error

### ISSUE THREAD

**Issue by agiani99** [Jonas-Verhellen/argenomic#6]
HI all,
I tried with attached yaml to change target, source and filter. 
I had in the meantime re-installed code (not the development branch though).
Got following errorTraceback (most recent call last):
  File "illuminate.py", line 74, in <module>
    illumination(omegaconf.OmegaConf.load(configuration.configuration_file))(configuration.generations)
  File "illuminate.py", line 27, in __call__
    self.initial_population()
  File "illuminate.py", line 39, in initial_population
    molecules = dataframe['molecule'].sample(n=self.initial_size).tolist()
  File "/usr/bin/anaconda3/envs/argenomic-stable/lib/python3.7/site-packages/pandas/core/generic.py", line 5061, in sample
    locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
  File "mtrand.pyx", line 946, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'

Apparently the code only works with given tests.
Btw pytest from README.md is missing in the release.
Best
Andrea

[config_az.txt](https://github.com/Jonas-Verhellen/Argenomic/files/4980311/config_az.txt)

**Comment by Jonas-Verhellen** [comment]
Hi Andrea,

That's a user error not a numpy error. 
You are trying to read in 1500 unique molecules from file that only contains 650.

Regards
Jonas

**Comment by agiani99** [comment]
Sorry I missed it...
Please close
Thx
Andrea


-----Original Message-----
