### ISSUE TITLE
Please consider Hydra

### ISSUE THREAD

**Issue by omry** [Jonas-Verhellen/argenomic#8]
Hi,
I am the author of OmegaConf (which you are already using) and Hydra (https://hydra.cc).
Looking at your project, I think you will benefit a lot by switching to Hydra.
Hydra builds on OmegaConf so it should be pretty straight forward.

[This blog post](https://medium.com/pytorch/hydra-a-fresh-look-at-configuration-for-machine-learning-projects-50583186b710?source=friends_link&sk=731951b8f758089290198398f63f9b09) is a pretty good intro to Hydra.

**Comment by Jonas-Verhellen** [comment]
@omry Thank you for the suggestion and the development of Hydra! Looking forward to your next project.

**Comment by omry** [comment]
Awesome!
Hydra is still under very active development so stay tuned.

Feel free to join the Hydra chat if you have any questions.
